# Limine Bootloader Configuration for FortressOS
timeout: 3
wallpaper: boot():/boot/splash.png
wallpaper_style: centered
backdrop: 1A1B26

/FortressOS (UEFI x86_64)
    protocol: limine
    kernel_path: boot():/boot/fortress.elf
    module_path: boot():/boot/initramfs.tar

/FortressOS (SMP 6D VMM Lifecycle Test)
    protocol: limine
    kernel_path: boot():/boot/fortress.elf
    module_path: boot():/boot/initramfs.tar
    kernel_cmdline: smp_memory_test=vmm_lifecycle usb_data=PARTUUID=06B2F06F-E31E-433E-AB53-4867516416E4 usb_data_mode=rw

/FortressOS (SMP 6B Memory Stress Test)
    protocol: limine
    kernel_path: boot():/boot/fortress.elf
    module_path: boot():/boot/initramfs.tar
    kernel_cmdline: smp_memory_test=stress usb_data=PARTUUID=06B2F06F-E31E-433E-AB53-4867516416E4 usb_data_mode=rw

