#!/usr/bin/env python3
"""Generate NASM %define constants from signal_frame.h for the restorer stub.

Reads SIGFRAME_OFF_* and SIGFRAME_V1_SIZE from the C header and emits a
matching signal_frame_asm.inc. Also emits SYS_SIGRETURN from syscall_abi.h.
Run at build time; the output file is a build artifact, not source.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HEADER = REPO / "src" / "include" / "signal_frame.h"
SYSCALL_ABI = REPO / "src" / "include" / "syscall_abi.h"
OUT = REPO / "build" / "signal_frame_asm.inc"


def extract_defines(path, pattern):
    result = {}
    text = path.read_text(encoding="utf-8")
    for m in re.finditer(pattern, text):
        name, value = m.group(1), m.group(2).strip()
        # Handle negative literals like (-8)
        value = value.strip("()")
        try:
            result[name] = int(value, 0)
        except ValueError:
            pass
    return result


def main():
    # Extract signal frame constants
    frame_defs = extract_defines(
        HEADER,
        r"#define\s+(SIGFRAME_[A-Z0-9_]+)\s+(\(?\-?\d+\)?)"
    )

    # Extract SYS_SIGRETURN from syscall_abi.h
    syscall_defs = extract_defines(
        SYSCALL_ABI,
        r"#define\s+(SYS_SIGRETURN)\s+(\d+)"
    )

    if not frame_defs:
        print(f"ERROR: No SIGFRAME_ defines found in {HEADER}", file=sys.stderr)
        sys.exit(1)

    if "SYS_SIGRETURN" not in syscall_defs:
        print(f"ERROR: SYS_SIGRETURN not found in {SYSCALL_ABI}", file=sys.stderr)
        sys.exit(1)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Auto-generated by scripts/gen_signal_frame_asm.py — DO NOT EDIT.",
        "; Source of truth: src/include/signal_frame.h and src/include/syscall_abi.h",
        "",
    ]

    # Emit SIGFRAME_ constants
    for name, value in sorted(frame_defs.items()):
        lines.append(f"%define {name} {value}")

    lines.append("")

    # Emit SYS_SIGRETURN
    lines.append(f"%define SYS_SIGRETURN {syscall_defs['SYS_SIGRETURN']}")

    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT} with {len(frame_defs)} SIGFRAME_ defines and SYS_SIGRETURN.")


if __name__ == "__main__":
    main()
